spring:
  application:
    name: config
  cloud:
    bus:
      ack:
        enabled: true
    config:
      server:
        git:
#          uri: https://github.com/fengerlong/config-repo
          basedir: E:\placeForTest\config\src\main\resources\config
          uri: http://sunrise.lan/ewp/config-repo.git
          username: fengerlong
          password: fengERlong0517
  rabbitmq:
    host: 192.168.10.204
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
management:
  security:
    enabled: false